#pragma once
#include "CoreMinimal.h"
#include "ELuxCharacter.generated.h"

UENUM(BlueprintType)
enum class ELuxCharacter : uint8 {
    ELC_MITSURUGI,
    ELC_MINA,
    ELC_TAKI,
    ELC_MAXI,
    ELC_VOLDO,
    ELC_SOPHITIA,
    ELC_SIEG,
    ELC_IVY,
    ELC_KILIK,
    ELC_XIANGHUA,
    ELC_YOSHIMITSU,
    ELC_NIGHTMARE,
    ELC_ASTAROTH,
    ELC_CERVANTES,
    ELC_RAPHAEL,
    ELC_TALIM,
    ELC_TIRA,
    ELC_ZASALAMEL,
    ELC_YOSHIMITSU2,
    ELC_GROH,
    ELC_AZWEL,
    ELC_GERALT,
    ELC_LESSER_LIZARDMAN,
    ELC_EVIL_KILIK,
    ELC_EVIL_GROH,
    ELC_BOSS_AZWEL,
    ELC_INFERNO,
    ELC_EDGEMASTER,
    ELC_CREATION,
    ELC_2B,
    ELC_CASSANDRA,
    ELC_AMY,
    ELC_HILDA,
    ELC_RAKSHA,
    ELC_SETSUKA,
    ELC_HWANG,
    ELC_STONE,
    ELC_STAR,
    ELC_REPTILE,
    ELC_SNOW,
    ELC_YELLOW,
    ELC_YELL,
    ENUM_MAX UMETA(Hidden),
};

