#pragma once
#include "CoreMinimal.h"
#include "ELuxPartSlot.generated.h"

UENUM(BlueprintType)
enum class ELuxPartSlot : uint8 {
    EPS_Mandatory_Neck,
    EPS_Mandatory_Tanima,
    EPS_Mandatory_UpperArm,
    EPS_Mandatory_Elbow,
    EPS_Mandatory_ForeArm,
    EPS_Mandatory_Hand,
    EPS_Mandatory_Chest,
    EPS_Mandatory_Stomach,
    EPS_Mandatory_Hip,
    EPS_Mandatory_Thigh,
    EPS_Mandatory_Knee,
    EPS_Mandatory_Shin,
    EPS_Mandatory_Ankle,
    EPS_Mandatory_Scalp,
    EPS_Mandatory_Hair,
    EPS_Mandatory_Face,
    EPS_Optional_Shoulder,
    EPS_Optional_UpperArm,
    EPS_Optional_Gauntlet,
    EPS_Optional_Necklace,
    EPS_Optional_ChestFit,
    EPS_Optional_ChestPlate,
    EPS_Optional_Skirt,
    EPS_Optional_Hem,
    EPS_Optional_Belt,
    EPS_Optional_UpperLeg,
    EPS_Optional_UnderShin,
    EPS_Optional_Shoes,
    EPS_Optional_Mantle,
    EPS_Optional_Head,
    EPS_Optional_Glasses,
    EPS_Optional_Cheek,
    EPS_Optional_BackCloth,
    EPS_Optional_Accessory,
    EPS_Optional_Maegami1,
    EPS_Optional_Maegami2,
    EPS_Racial_1,
    EPS_Racial_2,
    EPS_Racial_3,
    EPS_Racial_4,
    ENUM_MAX UMETA(Hidden),
};

