#pragma once
#include "CoreMinimal.h"
#include "ELuxFightStyle.generated.h"

UENUM(BlueprintType)
enum class ELuxFightStyle : uint8 {
    EFS_MITSURUGI,
    EFS_MINA,
    EFS_TAKI,
    EFS_MAXI,
    EFS_VOLDO,
    EFS_SOPHITIA,
    EFS_SIEG,
    EFS_IVY,
    EFS_KILIK,
    EFS_XIANGHUA,
    EFS_YOSHIMITSU,
    EFS_NIGHTMARE,
    EFS_ASTAROTH,
    EFS_CERVANTES,
    EFS_RAPHAEL,
    EFS_TALIM,
    EFS_TIRA,
    EFS_ZASALAMEL,
    EFS_YOSHIMITSU2,
    EFS_GROH,
    EFS_AZWEL,
    EFS_GERALT,
    EFS_LESSER_LIZARDMAN,
    EFS_EVIL_KILIK,
    EFS_EVIL_GROH,
    EFS_BOSS_AZWEL,
    EFS_INFERNO,
    EFS_EDGEMASTER,
    EFS_2B,
    EFS_CASSANDRA,
    EFS_AMY,
    EFS_HILDA,
    EFS_RAKSHA,
    EFS_SETSUKA,
    EFS_HWANG,
    EFS_STONE,
    EFS_STAR,
    EFS_REPTILE,
    EFS_SNOW,
    EFS_YELLOW,
    EFS_YELL,
    ENUM_MAX UMETA(Hidden),
    EFS_INVALID_ID = 0xFF,
};

