#pragma once
#include "CoreMinimal.h"
#include "ELuxBattleDummyMoveType.generated.h"

UENUM(BlueprintType)
enum class ELuxBattleDummyMoveType : uint8 {
    Off,
    Stand_Normal,
    Stand_AllStandingGuard,
    Stand_AllGuard,
    Stand_AllGuardOnce,
    Stand_AllGuardTwice,
    Stand_AllGuardThrice,
    Stand_FirstHitGuard,
    Stand_SecondHitGuard,
    Stand_RandomStandingGuard,
    Stand_RandomAllGuard,
    Stand_Jump,
    Crouch_Normal,
    Crouch_AllCrouchingGuard,
    Crouch_AllGuard,
    Crouch_AllGuardOnce,
    Crouch_AllGuardTwice,
    Crouch_AllGuardThrice,
    Crouch_FirstHitGuard,
    Crouch_SecondHitGuard,
    Crouch_RandomCrouchingGuard,
    Crouch_RandomAllGuard,
    Run_Right,
    Run_Left,
    Run_FrontStep,
    Run_BackStep,
    Run_RightStep,
    Run_LeftStep,
    Attack_AA,
    Attack_2A,
    Attack_BB,
    Attack_3B,
    Attack_K,
    Attack_2K,
    Attack_CE,
    Attack_SoulCharge,
    Attack_SoulAttack,
    ReversalEdge_Normal,
    ReversalEdge_Max,
    GuardImpact,
    MightyImpact,
    DownState_FaceUp,
    DownState_FaceDown,
    Playback_Slot1,
    Playback_Slot2,
    Playback_Slot3,
    Playback_Random,
    CommandList,
    DoNothing,
    DownState_None,
    DownState_Foward,
    DownState_Back,
    DownState_Left,
    DownState_Right,
    DownState_Standup,
    ENUM_MAX UMETA(Hidden),
};

