#pragma once
#include "CoreMinimal.h"
#include "ELuxTracePartsId.generated.h"

UENUM(BlueprintType)
enum class ELuxTracePartsId : uint8 {
    TRC_PT_NONE,
    TRC_PT_ARMS1,
    TRC_PT_ARMS2,
    TRC_PT_ARMS3,
    TRC_PT_ARMS4,
    TRC_PT_ARMS5,
    TRC_PT_ARMS6,
    TRC_PT_ARMS7,
    TRC_PT_ARMS8,
    TRC_PT_ARMS9,
    TRC_PT_TAIL,
    TRC_PT_MUNE1,
    TRC_PT_ATAMA,
    TRC_PT_KATA_R,
    TRC_PT_UDE_R,
    TRC_PT_TE_R,
    TRC_PT_KATA_L,
    TRC_PT_UDE_L,
    TRC_PT_TE_L,
    TRC_PT_KOSHI,
    TRC_PT_MOMO_R,
    TRC_PT_HIZA_R,
    TRC_PT_ASHI_R,
    TRC_PT_MOMO_L,
    TRC_PT_HIZA_L,
    TRC_PT_ASHI_L,
    TRC_PT_EYE_R,
    TRC_PT_EYE_L,
    TRC_PT_AUO1,
    TRC_PT_AUO2,
    TRC_PT_AUO3,
    TRC_PT_AUO4,
    TRC_PT_AUO5,
    TRC_PT_AUO6,
    TRC_PT_AUO7,
    TRC_PT_AUO8,
    TRC_PT_NM_OYA,
    TRC_PT_NM_HITO,
    TRC_PT_NM_NAKA,
    TRC_PT_SP_01,
    TRC_PT_SP_02,
    TRC_PT_SP_03,
    TRC_PT_SP_04,
    TRC_PT_SP_05,
    TRC_PT_SP_06,
    TRC_PT_SP_07,
    TRC_PT_SP_08,
    TRC_PT_SP_09,
    TRC_PT_MAX UMETA(Hidden),
};

