#pragma once
#include "CoreMinimal.h"
#include "ELuxBattleTutorialTaskType.generated.h"

UENUM(BlueprintType)
enum class ELuxBattleTutorialTaskType : uint8 {
    KO,
    Run,
    Step,
    CriticalEdge,
    SoulCharge,
    ReversalEdge,
    Revenge,
    Hit_AnyAttack,
    Hit_CrouchAttack,
    Hit_CrouchToStandAttack,
    Hit_SimultaneousInputAttack,
    Hit_RunAttack,
    Hit_BreakAttack,
    Hit_UnblockableAttack,
    Hit_BreakOrUnblockableAttack,
    Hit_Throw,
    Hit_FrontThrow,
    Hit_BackThrow,
    Hit_CriticalEdge,
    Hit_ReversalEdge,
    Guard_Any,
    Guard_Stand,
    Guard_Crouch,
    Escape_Throw,
    Escape_FrontThrow,
    Escape_BackThrow,
    Evade_VerticalAttack_ByRun,
    Evade_HighAttack_ByCrouch,
    Evade_LowAttack_ByJump,
    Evade_LowAttack_ByJumpAttack,
    Evade_Throw_ByCrouch,
    Evade_Throw_ByJump,
    Evade_Attack_ByAerialControl,
    Evade_ReversalEdge_ByRun,
    ReversalEdge_Parry,
    ReversalEdge_Input_ABK,
    ReversalEdge_Input_A,
    ReversalEdge_Input_B,
    ReversalEdge_Input_K,
    ReversalEdge_Input_G,
    ReversalEdge_Input_ABK_1st,
    ReversalEdge_Input_ABK_2nd,
    ReversalEdge_Input_B_1st,
    ReversalEdge_Input_B_2nd,
    ReversalEdge_Evasion,
    ReversalEdge_Win,
    Crush_ReversalEdge,
    Crush_GuardImpact,
    Ukemi,
    Rise,
    RollingRise,
    Rising_Attack,
    SideRolling,
    GuardImpact,
    ReverseImpact,
    CounterHit,
    LethalHit,
    PunishHit,
    WallHit,
    GuardBurst,
    Stun,
    SoulAttack,
    ENUM_MAX UMETA(Hidden),
};

