#pragma once
#include "CoreMinimal.h"
#include "ELuxPartsSE.generated.h"

UENUM(BlueprintType)
enum class ELuxPartsSE : uint8 {
    ESE_None,
    ESE_Mantle_Short = 0x10,
    ESE_Mnatle_Long,
    ESE_Mantle_Straw,
    ESE_Mantle_Leather,
    ESE_Mantle_Chain,
    ESE_Mantle_Feather,
    ESE_Arm_LightIron = 0x20,
    ESE_Arm_MediumIron,
    ESE_Arm_HeabyIron,
    ESE_Arm_Yoshimitsu,
    ESE_Arm_Rock,
    ESE_Arm_Gauntlet,
    ESE_Arm_Chain,
    ESE_Waist_ChainMail = 0x30,
    ESE_Waist_Iron,
    ESE_Waist_Leather,
    ESE_Waist_Bone,
    ESE_Waist_Gimmick,
    ESE_Waist_JapaneseArmor,
    ESE_Waist_Chain_Short,
    ESE_Waist_Chain_Long,
    ESE_Leg_Kimono = 0x40,
    ESE_Leg_Dress,
    ESE_Leg_LeatherPants,
    ESE_Leg_LightIron,
    ESE_Leg_MediumIron,
    ESE_Leg_HeavyIron,
    ESE_Leg_ClothSkirt,
    ESE_Leg_LeatherSkirt,
    ESE_Leg_Denim,
    ESE_Leg_CargoPants,
    ESE_Leg_Rock,
    ESE_Accessory_Bell = 0x50,
    ESE_Accessory_A,
    ESE_Accessory_B,
    ESE_Accessory_C,
    ESE_Accessory_D,
    ESE_Accessory_E,
    ESE_Accessory_F,
    ESE_Accessory_GunProp,
    ESE_Accessory_Beadroll,
    ESE_Accessory_Cat,
    ESE_Accessory_Machine_Gimmick,
    ESE_Footwear_Normal = 0x60,
    ESE_Footwear_Leather,
    ESE_Footwear_Pinheel,
    ESE_Footwear_Highheel,
    ESE_Footwear_StrawSandal,
    ESE_Footwear_Barefoot,
    ESE_Footwear_Clog,
    ESE_Footwear_LightIron,
    ESE_Footwear_HeavyIron,
    ESE_MAX UMETA(Hidden),
};

